development:
  adapter: postgresql
  encoding: unicode
  database: veggies_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: veggies_test
  host: localhost
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: veggies_production
  pool: 5
  username: teacup
  password: